version: '3.1'

services:
  teamcity:
    container_name: teamcity-server
    image: jetbrains/teamcity-server
    ports:
      - "8112:8111"
    volumes:
      - ./data_dir/teamcity-server-data:/data/teamcity_server/datadir
      - ./data_dir/teamcity-server-logs:/opt/teamcity/logs
    networks:
      - teamcity-net

  teamcity-agent:
    container_name: teamcity-agent
    build: .
    privileged: true
    volumes:
      - ./data_dir/teamcity-agent-conf:/data/teamcity_agent/conf
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
        - AGENT_NAME="Agent builder"
        - SERVER_URL=http://teamcity:8111
    networks:
      - teamcity-net

networks:
  teamcity-net:
    driver: bridge
